// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhI6COckLSfPKd4pBbIBXdZZMlZLewMAY',
    appId: '1:91161692539:web:166665ccb757995b5a95de',
    messagingSenderId: '91161692539',
    projectId: 'atozlab-lesson-reservation-app',
    authDomain: 'atozlab-lesson-reservation-app.firebaseapp.com',
    storageBucket: 'atozlab-lesson-reservation-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQEmqO71f2VVj00SHTGqS7lMRTgWZYGJk',
    appId: '1:91161692539:android:e04b22ddfcacfc815a95de',
    messagingSenderId: '91161692539',
    projectId: 'atozlab-lesson-reservation-app',
    storageBucket: 'atozlab-lesson-reservation-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK5QSmYvjve2zwzbGvtlvTuIGgF4wFgkE',
    appId: '1:91161692539:ios:c26b9ecd847c51b15a95de',
    messagingSenderId: '91161692539',
    projectId: 'atozlab-lesson-reservation-app',
    storageBucket: 'atozlab-lesson-reservation-app.firebasestorage.app',
    iosBundleId: 'com.example.atozSchoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK5QSmYvjve2zwzbGvtlvTuIGgF4wFgkE',
    appId: '1:91161692539:ios:c26b9ecd847c51b15a95de',
    messagingSenderId: '91161692539',
    projectId: 'atozlab-lesson-reservation-app',
    storageBucket: 'atozlab-lesson-reservation-app.firebasestorage.app',
    iosBundleId: 'com.example.atozSchoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhI6COckLSfPKd4pBbIBXdZZMlZLewMAY',
    appId: '1:91161692539:web:81f79523734b84145a95de',
    messagingSenderId: '91161692539',
    projectId: 'atozlab-lesson-reservation-app',
    authDomain: 'atozlab-lesson-reservation-app.firebaseapp.com',
    storageBucket: 'atozlab-lesson-reservation-app.firebasestorage.app',
  );
}
